### ISSUE TITLE
nonet requires rlang *less than* or equal to 0.3.0.1

### ISSUE THREAD

**Issue by lionel-** [GSLabDev/nonet#2]
This makes nonet incompatible with the next version of purrr which requires 0.3.1. Could you please fix? I plan to send purrr to CRAN within 2 weeks.

**Comment by vinodborole** [comment]
@AviralVijay-GSLab please check this

**Comment by AviralVijay-GSLab** [comment]
@lionel-  Thanks for informing, We have fixed the dependency.

**Comment by AviralVijay-GSLab** [comment]
fixed
